#!/usr/local/bin/python

# Print every directory in the $PATH environment variable on a separate line
import sys
import os

if len(sys.argv) > 1 and sys.argv[1] == "-h":
    print ("\n    'showpath' (in order) displays all directories in the" +
           " $PATH variable\n")
else:
    path = os.environ.get("PATH")

    for s in path.split(':'):
        print s
